language: ruby
services:
  - mysql
rvm:
  - 1.9.3
  - 2.0.0
env:
  global:
    - PLUGIN_NAME=redmine_select2
    - DB=mysql
  matrix:
    - REDMINE_VER=2.1.6
    - REDMINE_VER=2.2.4
    - REDMINE_VER=2.3.3

before_install:
  - export REDMINE_PATH=$HOME/redmine
  - git clone --depth=1 --branch=$REDMINE_VER https://github.com/redmine/redmine.git $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

install:
  - bundle install

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME

