language: ruby

services:
  - mysql

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

env:
  - REDMINE_VER=2.1.6
  - REDMINE_VER=2.2.4
  - REDMINE_VER=2.3.3
  - REDMINE_VER=2.4.1

matrix:
  exclude:
    - rvm: 1.8.7
      env: REDMINE_VER=2.3.3
    - rvm: 1.8.7
      env: REDMINE_VER=2.4.1
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4

before_install:
  - export PLUGIN_NAME=redmine__select2
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - export DBVER=`if [ "$TRAVIS_RUBY_VERSION" = "1.8.7" ] && [ "$DB" = "mysql" ]; then echo "mysql-1.8.7"; else echo "$DB"; fi`
  - cp config/database-$DBVER-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME
